export const CASE_REGISTER_REQUEST ='CASE_REGISTER_REQUEST'
export const CASE_REGISTER_SUCCESS ='CASE_REGISTER_SUCCESS'
export const CASE_REGISTER_FAIL ='CASE_REGISTER_FAIL'

export const CASE_LIST_REQUEST ='CASE_LIST_REQUEST'
export const CASE_LIST_SUCCESS ='CASE_LIST_SUCCESS'
export const CASE_LIST_FAIL ='CASE_LIST_FAIL'
export const CASE_LIST_RESET ='CASE_LIST_RESET'


export const CASE_DELETE_REQUEST='CASE_DELETE_REQUEST'
export const CASE_DELETE_SUCCESS='CASE_DELETE_SUCCESS'
export const CASE_DELETE_FAIL='CASE_DELETE_FAIL'

export const CASE_ACCEPT_REQUEST='CASE_ACCEPT_REQUEST'
export const CASE_ACCEPT_SUCCESS='CASE_ACCEPT_SUCCESS'
export const CASE_ACCEPT_FAIL='CASE_ACCEPT_FAIL'