export const LAWYER_LIST_REQUEST='LAWYER_LIST_REQUEST'
export const LAWYER_LIST_SUCCESS='LAWYER_LIST_SUCCESS'
export const LAWYER_LIST_FAIL='LAWYER_LIST_FAIL'

export const LAWYER_DETAILS_REQUEST='LAWYER_DETAILS_REQUEST'
export const LAWYER_DETAILS_SUCCESS='LAWYER_DETAILS_SUCCESS'
export const LAWYER_DETAILS_FAIL='LAWYER_DETAILS_FAIL'