export const LAWYER_LIST_REQUEST='LAWYER_LIST_REQUEST'
export const LAWYER_LIST_SUCCESS='LAWYER_LIST_SUCCESS'
export const LAWYER_LIST_FAIL='LAWYER_LIST_FAIL'

export const LAWYER_DETAILS_REQUEST='LAWYER_DETAILS_REQUEST'
export const LAWYER_DETAILS_SUCCESS='LAWYER_DETAILS_SUCCESS'
export const LAWYER_DETAILS_FAIL='LAWYER_DETAILS_FAIL'
export const LAWYER_DETAILS_RESET='LAWYER_DETAILS_RESET'

export const LAWYER_REVIEW_REQUEST='LAWYER_REVIEW_REQUEST'
export const LAWYER_REVIEW_SUCCESS='LAWYER_REVIEW_SUCCESS'
export const LAWYER_REVIEW_FAIL='LAWYER_REVIEW_FAIL'
export const LAWYER_REVIEW_RESET='LAWYER_REVIEW_RESET'

export const LAWYER_DELETE_REQUEST='LAWYER_DELETE_REQUEST'
export const LAWYER_DELETE_SUCCESS='LAWYER_DELETE_SUCCESS'
export const LAWYER_DELETE_FAIL='LAWYER_DELETE_FAIL'

export const LAWYER_VERIFY_REQUEST='LAWYER_VERIFY_REQUEST'
export const LAWYER_VERIFY_SUCCESS='LAWYER_VERIFY_SUCCESS'
export const LAWYER_VERIFY_FAIL='LAWYER_VERIFY_FAIL'

export const LAWYER_TOP_REQUEST = 'LAWYER_TOP_REQUEST'
export const LAWYER_TOP_SUCCESS = 'LAWYER_TOP_SUCCESS'
export const LAWYER_TOP_FAIL = 'LAWYER_TOP_FAIL'